# fly.toml app configuration file generated for irocar on 2023-05-19T09:44:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "irocar"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
